# This file contains values from Cookiecutter

default_context:
  project_name: "word2vec-ext"
  project_description: "Extensions set for Word2Vec model analysis"
  organization: "word2vec-ext"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "word2vec-ext"
  email: "mihailyazenok@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
